### ISSUE TITLE
Fails to build both without and with `--lto`

### ISSUE THREAD

**Issue by o-pikozh** [Rakete1111/stackcpp#1]
Maybe I am doing something wrong, but I get the following results:

  - [without `--lto`](https://github.com/Rakete1111/stackcpp/files/1212075/without-lto.txt)
  - [with `--lto`](https://github.com/Rakete1111/stackcpp/files/1212074/with-lto.txt)

**Comment by Rakete1111** [comment]
Aha, this is [CWG #2148](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-defects.html#2148). It compiles for me because I'm using the latest releases of gcc and clang, but you are using a version where the defect was not fixed yet.

I'll implement a workaround. Thanks for reporting!
